language: r

sudo: required

apt_packages:
 - openjdk-7-jre

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

before_install: 
  - echo "options(repos = c(CRAN='http://cran.r-project.org'))" > ~/.Rprofile
  - R --version
  - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
  - export PATH=$PATH:$JAVA_HOME/bin
  - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/lib/amd64:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
  - R CMD javareconf

after_success:
  - Rscript -e 'covr::coveralls()'
