sudo: required

language: r

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

before_install: echo "options(repos = c(CRAN='http://cran.r-project.org'))" > ~/.Rprofile

after_success:
  - Rscript -e 'covr::coveralls()'
