language: r

r:
  #- oldrel
  - release
  - devel

cache: packages

sudo: false

jdk:
  - oraclejdk8

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

before_install: 
  - echo "options(repos = c(CRAN='http://cran.r-project.org'))" > ~/.Rprofile
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - export PATH=$PATH:$JAVA_HOME/bin
  - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/lib/amd64:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
  - R CMD javareconf
  
script:
  - R CMD build .
  - travis_wait R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::coveralls()'
